name: flutter_obs
description: "a easy flutter state management, the source code is less than 100, but you can use it to implement global and local states"
version: 1.0.1
homepage: https://github.com/luoyi58624/flutter_obs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: