name: flutter_obs
description: "A easy state management, It is an enhanced version of ValueNotifier"
version: 1.2.3
homepage: https://github.com/luoyi58624/flutter_obs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
